parameters:
    kernel.orm_mapping_dir: "%kernel.project_dir%/config/orm"

doctrine:
    dbal:
        connections:
            default:
                driver: 'pdo_pgsql'
                charset: utf8
                dbname: '%env(resolve:DATABASE_NAME)%'
                host: '%env(resolve:DATABASE_HOST)%'
                server_version: 13.6
                port: '5432'
                user: '%env(resolve:DATABASE_USER)%'
                password: '%env(resolve:DATABASE_PASS)%'
                mapping_types:
                    enum: string

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"

        entity_managers:
            default:
                connection: default
                auto_mapping: false
                mappings:
                    account:
                        type: xml
                        dir: "%kernel.orm_mapping_dir%/account"
                        prefix: "Component\\Account\\Model"
                        is_bundle: false
                    exchange:
                        type: xml
                        dir: "%kernel.orm_mapping_dir%/exchange"
                        prefix: "Component\\Exchange\\Model"
                        is_bundle: false
                    transaction:
                        type: xml
                        dir: "%kernel.orm_mapping_dir%/transaction"
                        prefix: "Component\\Transaction\\Model"
                        is_bundle: false
                    user:
                        type: xml
                        dir: "%kernel.orm_mapping_dir%/user"
                        prefix: "Component\\User\\Model"
                        is_bundle: false

when@prod:
    doctrine:
        orm:
            metadata_cache_driver: apc