version: '3.9'

services:
    dev:
        build:
            context: ../../
            args:
                BUILD_ROLE: "dev"
        container_name: ${DEV_CONTAINER_NAME}
        environment:
            APP_HOST: localhost
            GITLAB_ACCESS_TOKEN: ${GITLAB_ACCESS_TOKEN}
            XDEBUG_MODE: coverage
        volumes:
            - "../../:/var/www/app"
        ports:
            - ${WEB_APP_PORT}:80

    postgres:
        container_name: ${PG_CONTAINER_NAME}
        image: postgres:13.6
        environment:
            POSTGRESQL_FSYNC: 'off'
            POSTGRES_USER: ${DB_USER}
            PGUSER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        healthcheck:
            test: [ "CMD", "pg_isready" ]
            interval: 10s
            timeout: 2s
            retries: 3
            start_period: 30s
        ports:
            - ${DB_PORT}:5432
